# Generated by Django 4.1.1 on 2023-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='Desconocida', max_length=200, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='Desconocida', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Pais'),
        ),
    ]
